/*
PUT FRONT-END CONSTANTS IN HERE THAT WILL BE COMMITTED TO THE REPO
DON'T PUT SENSITIVE CONSTANTS IN HERE [ADD THOSE TO private_constants]
*/

/* 10. INCREMENT THE APP VERSION NUMBER TO 0.0003 */
const FRONTEND_VERSION = 0.0005;
const APP_TITLE = "Jalopy Starter";
const SKIP_STALE_TOKEN_CHECK = true;
const QUOTES_API_KEY = 'venus-129';